name: CD

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
      K8S_MANIFEST_PATH: ${{ secrets.K8S_MANIFEST_PATH || 'k8s' }}
      DEPLOYMENT_NAME: ${{ secrets.DEPLOYMENT_NAME || 'gratitudeapp' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        if: ${{ secrets.AWS_ROLE_ARN != '' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build image
        id: build
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          IMAGE_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${IMAGE_TAG}
          echo "IMAGE_URI=${IMAGE_URI}" >> "$GITHUB_OUTPUT"
          docker build -t "$IMAGE_URI" .

      - name: Trivy image scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: image
          image-ref: ${{ steps.build.outputs.IMAGE_URI }}
          severity: HIGH,CRITICAL
          exit-code: "1"

      - name: Push image
        run: docker push "${{ steps.build.outputs.IMAGE_URI }}"

      - name: Configure kubeconfig
        run: |
          if [ -n "${KUBECONFIG_B64}" ]; then
            echo "${KUBECONFIG_B64}" | base64 -d > "$RUNNER_TEMP/kubeconfig"
            export KUBECONFIG="$RUNNER_TEMP/kubeconfig"
          else
            aws eks update-kubeconfig --name "${EKS_CLUSTER_NAME}" --region "${AWS_REGION}"
          fi
        env:
          KUBECONFIG_B64: ${{ secrets.KUBECONFIG_B64 }}

      - name: Deploy manifests
        run: |
          kubectl apply -f "${K8S_MANIFEST_PATH}"
          kubectl rollout status deployment/${DEPLOYMENT_NAME}
