name: CI

on:
  pull_request:

jobs:
  ci:
    runs-on: self-hosted
    env:
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Run tests
        run: npm test

      - name: SonarQube scan
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          args: >-
            -Dsonar.projectKey=gratitudeapp
            -Dsonar.sources=.

      - name: SonarQube quality gate
        uses: sonarsource/sonarqube-quality-gate-action@v1.1.0
        timeout-minutes: 5

      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          severity: HIGH,CRITICAL
          exit-code: "1"
