name: Reusable Build + Scan + Push

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      service_path:
        required: true
        type: string
      ecr_repo:
        required: true
        type: string
      image_tag:
        required: true
        type: string

jobs:
  build_scan_push:
    runs-on: [self-hosted, linux, x64, gratitude-runner]
    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_BASE: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker build cache
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache-${{ inputs.service_name }}
          key: buildx-${{ runner.os }}-${{ inputs.service_name }}-${{ github.sha }}
          restore-keys: |
            buildx-${{ runner.os }}-${{ inputs.service_name }}-

      - name: Build image (no push)
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.service_path }}
          file: ${{ inputs.service_path }}/Dockerfile
          push: false
          tags: |
            ${{ env.ECR_BASE }}/${{ inputs.ecr_repo }}:${{ inputs.image_tag }}
          cache-from: type=local,src=/tmp/.buildx-cache-${{ inputs.service_name }}
          cache-to: type=local,dest=/tmp/.buildx-cache-${{ inputs.service_name }}-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache-${{ inputs.service_name }}
          mv /tmp/.buildx-cache-${{ inputs.service_name }}-new /tmp/.buildx-cache-${{ inputs.service_name }}

      - name: SonarQube scan
        if: ${{ secrets.SONAR_HOST_URL != '' && secrets.SONAR_TOKEN != '' }}
        run: |
          docker run --rm \
            -e SONAR_HOST_URL="${{ secrets.SONAR_HOST_URL }}" \
            -e SONAR_TOKEN="${{ secrets.SONAR_TOKEN }}" \
            -v "${{ github.workspace }}:/usr/src" \
            sonarsource/sonar-scanner-cli:latest \
            -Dsonar.projectKey=gratitudeapp-${{ inputs.service_name }} \
            -Dsonar.sources=${{ inputs.service_path }} \
            -Dsonar.sourceEncoding=UTF-8

      - name: Trivy fs scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          scan-ref: ${{ inputs.service_path }}
          format: table
          exit-code: "1"
          severity: "CRITICAL,HIGH"

      - name: Trivy image scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.ECR_BASE }}/${{ inputs.ecr_repo }}:${{ inputs.image_tag }}
          format: table
          exit-code: "1"
          severity: "CRITICAL,HIGH"

      - name: Push image to ECR
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.service_path }}
          file: ${{ inputs.service_path }}/Dockerfile
          push: true
          tags: |
            ${{ env.ECR_BASE }}/${{ inputs.ecr_repo }}:${{ inputs.image_tag }}
